### PR TITLE
Pretty showing  other examples in table

### PR DESCRIPTION
**Pull request by jfoclpf**
Provide Markdown table for pretty showing other examples, number 8 was repeated. In the scope of request made here: https://github.com/GeoTIFF/georaster-layer-for-leaflet/issues/145#issuecomment-2045860235

### CODE REVIEW

**Comment by jfoclpf** [comment]
Table Result can be seen here: https://github.com/jfoclpf/georaster-layer-for-leaflet-example/tree/patch-1

**Comment by jfoclpf** [comment]
@DanielJDufour any time frame when you will check this PR? Thanks

**Comment by DanielJDufour** [comment]
Hey, I'll check this on Friday or Saturday! Thank you!! :-)

**Comment by jfoclpf** [comment]
Thanks :)

**Review by DanielJDufour — CHANGES_REQUESTED** [review]
looks great! only change I would request is the "Display a COG in an Angular Application" example doesn't have a live demo, so, I think we could have `-` or `n/a` instead of the link to the package.json.

**Review by jfoclpf — COMMENTED** [review]
as requested

**Comment by jfoclpf** [comment]
@DanielJDufour I edited as requested, tell me what you think

**Pull request merged**
