### PR TITLE
Create GeoTIFF directory, readme.me therein and add also a GeoTIFF file

### PR DESCRIPTION
**Pull request by jfoclpf**

### CODE REVIEW

**Comment by DanielJDufour** [comment]
Looks like a great GeoTIFF!  I'm curious, what's the source of the elevation data?  Would you be interested in contributing it to https://github.com/geotiff/test-data ?  It is a repository of testing data used by a bunch of different projects!

**Comment by jfoclpf** [comment]
Hi @DanielJDufour 

The source is the new [DEM (Digital Elevation Model)](https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model) from Copernicus.

The latest DEM GeoTIFF files from Copernicus not only are available in WGS84, but also give you already the height over sea level.

These GeoTIFF files are presented as tiles that can be fetched from the Copernicus PRISM project on the following webiste: https://sso.demf.pass.copernicus.eu (a registered account is necessary, but it's free).

Exemple here to download all the tiles for Portugal (mainland, Azores and Madeira)

[![enter image description here][1]][1]

Afterwards, in the download options we should select `Projection: WGS-84`, `Format: TIFF` and `Interpolation: Bilinear`.

Then I clip it according to the GeoJSON of the municipality of Lisbon.

Is that (repo https://github.com/geotiff/test-data) a place to reference official geoTiffs?


  [1]: https://i.stack.imgur.com/uRytH.jpg

**Comment by jfoclpf** [comment]
@DanielJDufour did you forget this PR?
It's important because [this](https://geotiff.github.io/georaster-layer-for-leaflet-example/examples/elevation.html) example on this repo is not dependent on a TIF file located on my server

**Comment by jfoclpf** [comment]
It's here: https://github.com/GeoTIFF/georaster-layer-for-leaflet-example/blob/master/examples/elevation.html#L36

**Comment by DanielJDufour** [comment]
Hi, sorry about that!  I'll merge this right away.

**Comment by DanielJDufour** [comment]
Sorry again for missing this.  The only requirements for adding a tiff to https://github.com/geotiff/test-data are:
-  file is relatively small (less than 5mb) making it quick to download all the test files
- file is in public domain or has a license that allows it to be shared
- original data source is clear

It doesn't have to be the raw original or official tif.  Clipped is okay as long as we know where it came from.

Hope this helps!

**Comment by jfoclpf** [comment]
Done it https://github.com/GeoTIFF/test-data/pull/2

**Pull request merged**
